spring.application.name=microservicio_ranking
server.port=8010
#server.port=8030
spring.profiles.active=test

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
